# Generated by Django 4.2.6 on 2024-09-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Hotel FAQS'},
        ),
    ]
