# Generated by Django 4.2.6 on 2024-09-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_roomtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Room Types'},
        ),
    ]
