# Generated by Django 4.2.6 on 2024-09-29 15:24

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_booking_email_alter_booking_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='success_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', blank=True, length=10, max_length=20, null=True, prefix='', unique=True),
        ),
    ]
